# Informasi Proyek
site_name: Nama Situs Anda
site_description: Deskripsi Situs Anda
site_author: Nama Anda
site_url: https://alamat-situs-anda.com

# Tema
theme:
  name: 'readthedocs'  # Tema Material Design (Anda perlu menginstal mkdocs-material)

# Navigasi
nav:
  - Beranda: index.md
  - Persiapan: persiapan.md
  - environment: env.md
 # - FAQ: faq.md
 # - Kontak: contact.md

# Ekstensi Markdown
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

# Plugin (Opsional)
plugins:
#  - search
#  - mkdocs-git-revision-date-localized-plugin

# Pengaturan Lainnya
strict: true

