# Generated by Django 4.2.3 on 2023-07-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Khazanah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_khazanah', models.CharField(max_length=100)),
                ('lokasi_penggunaan', models.CharField(max_length=200)),
                ('kurun_waktu_arsip', models.CharField(max_length=50)),
                ('jenis_arsip', models.CharField(max_length=50)),
            ],
        ),
    ]
