# Generated by Django 4.2.3 on 2023-08-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khazanah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pabrik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pabrik', models.CharField(max_length=100)),
                ('negara', models.CharField(max_length=100)),
                ('lokasi', models.CharField(max_length=200)),
            ],
        ),
    ]
