# Generated by Django 4.2.3 on 2023-08-02 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khazanah', '0002_pabrik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_inventaris', models.CharField(max_length=50)),
                ('waktu_produksi_kertas', models.DateTimeField()),
                ('kondisi_fisik_kertas', models.CharField(max_length=100)),
                ('panjang_kertas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lebar_kertas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('warna_kertas', models.CharField(max_length=50)),
                ('gramatur_kertas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tingkat_keasaman', models.CharField(max_length=50)),
                ('motif_watermark', models.CharField(max_length=100)),
                ('posisi_watermark', models.CharField(max_length=50)),
                ('panjang_watermark', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lebar_watermark', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif_countermark', models.CharField(max_length=100)),
                ('posisi_countermark', models.CharField(max_length=50)),
                ('panjang_countermark', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lebar_countermark', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jarak_antara_kolom_garis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('khazanah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khazanah.khazanah')),
                ('pabrik_kertas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khazanah.pabrik')),
            ],
        ),
    ]
