# Generated by Django 4.2.3 on 2023-08-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khazanah', '0003_transaksi'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='gambar_countermark',
            field=models.ImageField(default='default_image.jpg', upload_to='countermark/'),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='gambar_watermark',
            field=models.ImageField(default='default_image.jpg', upload_to='watermark/'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='waktu_produksi_kertas',
            field=models.DateField(),
        ),
    ]
