# Generated by Django 4.2.3 on 2023-08-10 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khazanah', '0004_transaksi_gambar_countermark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisKertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kertas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KondisiFisikKertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kondisi_fisik_kertas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MotifCountermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif_countermark', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MotifWatermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif_watermark', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PosisiCountermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posisi_countermark', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PosisiWatermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posisi_watermark', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WarnaKertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warna_kertas', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='kondisi_fisik_kertas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khazanah.kondisifisikkertas'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='motif_countermark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khazanah.motifcountermark'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='motif_watermark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khazanah.motifwatermark'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='posisi_countermark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khazanah.posisicountermark'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='posisi_watermark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khazanah.posisiwatermark'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='warna_kertas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khazanah.warnakertas'),
        ),
    ]
