# Generated by Django 4.2.3 on 2023-08-10 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khazanah', '0005_jeniskertas_kondisifisikkertas_motifcountermark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='jarak_garis',
            field=models.ImageField(default='default_image.jpg', upload_to='jarak_garis/'),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='jenis_kertas',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='khazanah.jeniskertas'),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='ketebalan_kertas',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='kurun_waktu_arsip',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='lembar_kertas',
            field=models.ImageField(default='default_image.jpg', upload_to='lembar_kertas/'),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='lokasi_penggunaan',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='ukuran_countermark',
            field=models.ImageField(default='default_image.jpg', upload_to='ukuran_countermark/'),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='ukuran_watermark',
            field=models.ImageField(default='default_image.jpg', upload_to='ukuran_watermark/'),
        ),
    ]
