# Generated by Django 4.2.3 on 2023-08-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khazanah', '0006_transaksi_jarak_garis_transaksi_jenis_kertas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='kurun_waktu_arsip',
            field=models.DateField(default='1970-01-01'),
        ),
    ]
