# Generated by Django 4.2.3 on 2023-08-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khazanah', '0007_alter_transaksi_kurun_waktu_arsip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaksi',
            options={'verbose_name_plural': 'Data Watermark'},
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='gramatur_kertas',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gramatur Kertas (gr)'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='tingkat_keasaman',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
