# Generated by Django 4.2.3 on 2023-08-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khazanah', '0009_remove_transaksi_kurun_waktu_arsip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='kurun_waktu_arsip',
            field=models.CharField(default='-', max_length=7),
        ),
    ]
