# Generated by Django 4.2.3 on 2023-08-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khazanah', '0010_transaksi_kurun_waktu_arsip'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='bulan_kurun_waktu',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='tahun_kurun_waktu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='kurun_waktu_arsip',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
